### ISSUE TITLE
Panic on initialization (MacOS M1) thru tun interface

### ISSUE THREAD

**Issue by andrew-morris** [sundruid/muonfp#1]
Not sure what info would be the most helpful but:

```
$ ./muonfp utun4
Listening on interface: utun4
thread 'main' panicked at /Users/andrew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pnet_datalink-0.29.0/src/bpf.rs:404:44:
misaligned pointer dereference: address must be a multiple of 0x4 but is 0x140809e0e
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread caused non-unwinding panic. aborting.
Abort trap: 6
```

This bug happened on a virtual interface that's basically a tap. Let me know what I can provide to help troubleshoot. 

```
$ rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)
$ uname -a
Darwin marathon 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
```

**Comment by sundruid** [comment]
Crate update in pnet appears to have solved the panic problem. Also a related cloud virtualization problem was solved. Note that you most likely will not see any fingerprints if tapping a utun interface unless you are on the host side of the traffic. Needs further testing.
